# -*- coding: utf-8 -*-
"""prakalgo13

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LXF4csn0yHEd0Y1TUTwhgLfCAvuYOpjO
"""

nilai_siswa = [85, 90, 78, 92, 88]
rata_rata_kelas = sum(nilai_siswa) / len(nilai_siswa)
print("Rata-rata nilai kelas:", rata_rata_kelas)
siswa_diatas_rata = [nilai for nilai in nilai_siswa if nilai > rata_rata_kelas]
print("Siswa yang mendapatkan nilai di atas rata-rata:", siswa_diatas_rata)

def konversi_mata_uang(local_currency, exchange_rate):
    jumlah_uang_local = float(input("Masukkan jumlah uang dalam mata uang lokal: "))
    jumlah_uang_asing = jumlah_uang_local * exchange_rate
    print(f"{jumlah_uang_local} {local_currency} setara dengan {jumlah_uang_asing} mata uang asing.")

kurs_dolar_us = 0.000064695395
konversi_mata_uang("Rupiah", kurs_dolar_us)

class Proyek:
    def __init__(self, nama, status, estimasi_waktu):
        self.nama = nama
        self.status = status
        self.estimasi_waktu = estimasi_waktu

    def __str__(self):
        return f"Proyek: {self.nama}, Status: {self.status}, Estimasi Waktu: {self.estimasi_waktu} hari"

def main():
    proyek1 = Proyek("Proyek A", "Dalam pengerjaan", 10)
    proyek2 = Proyek("Proyek B", "Selesai", 15)
    proyek3 = Proyek("Proyek C", "Dalam pengerjaan", 8)

    daftar_proyek = [proyek1, proyek2, proyek3]

    proyek_dalam_pengerjaan = [proyek for proyek in daftar_proyek if proyek.status == "Dalam pengerjaan"]
    proyek_dalam_pengerjaan_sorted = sorted(proyek_dalam_pengerjaan, key=lambda x: x.estimasi_waktu)

    print("Proyek yang masih dalam pengerjaan:")
    for proyek in proyek_dalam_pengerjaan_sorted:
        print(proyek)

if __name__ == "__main__":
    main()